# --- General configurations ---
# x-prefix and yaml anchor

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

# --- Project containers ---
services:
  nginx:
    init: true
    build: ./requirements/nginx
    container_name: inception-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wp:/var/www/html
      - log_nginx:/var/log/nginx
    # depends_on:
    #   - wordpress
    #   - mariadb
    restart: always
    # environment:
    networks:
      - inception-network
    secrets:
      - nginx_certificate
      - nginx_private_key 
    <<: *logging

  wordpress:
    init: true
    build: ./requirements/wordpress
    container_name: inception-wordpress
    # depends_on: mariadb
    restart: always
    # environment:
    networks:
      - inception-network
    expose:
      - 9000
    volumes:
      - wp:/var/www/html
    <<: *logging

  mariadb:
    init: true
    build: ./requirements/mariadb
    container_name: inception-mariadb
    restart: unless-stopped
    # environment:
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
      - log_mariadb:/var/log/mysql 
    networks:
      - inception-network
    <<: *logging

# --- Volumes & Networks definitions ---
volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/mariadb
  wp:
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/wordpress

  log_nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LOG_DIR}/nginx
  log_mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LOG_DIR}/mariadb

networks:
  inception-network:
    name: inception-network

secrets:
  nginx_certificate:
    file: .secrets/certs/shonakam.42.fr.crt
  nginx_private_key:
    file: .secrets/certs/shonakam.42.fr.key

# --- References ---
# https://docs.docker.com/reference/compose-file/services/
# https://docs.docker.com/reference/compose-file/extension/  -- x-prefix and yaml anchor
